version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:21

    working_directory: ~/jupyter-image

    steps:
      - checkout

      - setup_remote_docker

      - run: |
          gcloud-auth --with-docker
          ./build.sh
