version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:113

    working_directory: ~/jupyter-image

    steps:
      - checkout

      - setup_remote_docker

      - run: |
          docker build -t quartic/jupyter:${CIRCLE_BUILD_NUM} .

      - run:
            name: Run tests
            # See https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
            command: |
              docker create --name test quartic/jupyter:${CIRCLE_BUILD_NUM} sudo -E -u jovyan /home/jovyan/test/run_tests.sh
              # This permission change (along with the -a below) seems to be necessary to ensure
              # the quartic user inside the container can write to the test directory.
              chmod -R a+rw $(pwd)/test
              docker cp -a $(pwd)/test test:/home/jovyan/test
              docker start -a test
      - run: |
          gcloud-auth --with-docker
          ./build.sh