version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    working_directory: ~/jupyter-image

    steps:
      - checkout

      - setup_remote_docker

      - run: |
          apk --no-cache add curl docker
          curl https://raw.githubusercontent.com/quartictech/circleci-utils/develop/circleci-gcloud-login-2.0 | bash
      - run: |
          ./build.sh
