version: 2
jobs:
  build:
    docker:
      - image: docker

    working_directory: ~/jupyter-image

    steps:
      - checkout

      - setup_remote_docker:

      - run: |
          curl https://raw.githubusercontent.com/quartictech/circleci-utils/develop/circleci-gcloud-login | sh
          ./build.sh