version: 2

jobs:
  build:
    docker:
      - image: quartic/uber-builder:144

    working_directory: ~/jupyter-image

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build Docker image
          command: docker build -t jupyter .

      - run:
          name: GCloud auth
          command: google-cloud-auth --with-docker

      - run:
          name: Publish Docker image
          command: docker-tag-and-push jupyter ${CIRCLE_BUILD_NUM}
